services:
  couchbase:
    build: ./couchbase
    container_name: couchbase-1
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "11210:11210"
    env_file:
      - .env
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME
      - COUCHBASE_ADMINISTRATOR_PASSWORD
    healthcheck:
      test: ["CMD", "curl", "-u", "${COUCHBASE_ADMINISTRATOR_USERNAME}:${COUCHBASE_ADMINISTRATOR_PASSWORD}", "-f", "http://localhost:8091/pools/default"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - cb_data:/opt/couchbase/var

  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      couchbase:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build:
      context: .
      dockerfile: django_panel/Dockerfile
    container_name: django
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      couchbase:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cb_data:
