services:
  couchbase:
    image: couchbase:community-7.1.1
    ports:
      - "8091:8091"
      - "8092:8092"
      - "11210:11210"
    env_file:
      - .env
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME
      - COUCHBASE_ADMINISTRATOR_PASSWORD
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/pools"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - cb_data:/opt/couchbase/var

  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - couchbase

  django:
    build:
      context: .
      dockerfile: django_panel/Dockerfile
    container_name: django
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - couchbase

volumes:
  cb_data:
