# Generated by Django 5.2.1 on 2025-05-16 21:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelDoc',
            fields=[
                ('level_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProgressDoc',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('points', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('passedLevel', models.IntegerField(default=0)),
                ('items', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progresses',
                'managed': True,
            },
        ),
    ]
